-- 1. Criar tabela de fotos enviadas por convidados
CREATE TABLE IF NOT EXISTS guest_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_name TEXT NOT NULL,
  image_url TEXT NOT NULL,
  ip_address TEXT,
  is_approved BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Enable Row Level Security
ALTER TABLE guest_photos ENABLE ROW LEVEL SECURITY;

-- 3. Política: qualquer um pode inserir (convidado enviar foto)
CREATE POLICY "Anyone can insert guest photos"
  ON guest_photos FOR INSERT
  TO anon
  WITH CHECK (true);

-- 4. Política: público só vê fotos aprovadas
CREATE POLICY "Anyone can view approved photos"
  ON guest_photos FOR SELECT
  TO anon
  USING (is_approved = true);

-- 5. Política: autenticados (admin) podem ver/gerenciar tudo
CREATE POLICY "Authenticated users can manage guest photos"
  ON guest_photos FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- 6. Bucket de storage (roda no SQL Editor do Supabase)
-- Caso o bucket já exista, esse comando é ignorado
insert into storage.buckets (id, name, public)
values ('guest_photos', 'guest_photos', true)
on conflict (id) do nothing;

-- 7. Política de storage: qualquer um pode fazer upload
create policy "Anyone can upload to guest_photos"
  on storage.objects for insert
  to anon
  with check (bucket_id = 'guest_photos');

-- 8. Política de storage: público pode ler
create policy "Anyone can view guest_photos"
  on storage.objects for select
  to anon
  using (bucket_id = 'guest_photos');

-- 9. Política de storage: admin pode gerenciar tudo
create policy "Authenticated users can manage guest_photos objects"
  on storage.objects for all
  to authenticated
  using (bucket_id = 'guest_photos')
  with check (bucket_id = 'guest_photos');

-- 10. Coluna de configuração: aprovação automática de fotos
ALTER TABLE event_info ADD COLUMN IF NOT EXISTS auto_approve_photos BOOLEAN DEFAULT true;
